# Generated by Django 4.2 on 2025-04-04 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'db_table': 'categories',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'default_related_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Позиция меню',
                'verbose_name_plural': 'Позиции меню',
                'db_table': 'items',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'default_related_name': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Убедитесь, что количество позиции в заказе указано верно, мы не сможем приготовить меньше 1 блюда и больше 999.'), django.core.validators.MaxValueValidator(999, 'Убедитесь, что количество позиции в заказе указано верно, мы не сможем приготовить меньше 1 блюда и больше 999.')], verbose_name='Количество экземпляров позиции в заказе.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='orders.item', verbose_name='Позиция в заказе клиента')),
            ],
            options={
                'verbose_name': 'Позиция в заказе',
                'verbose_name_plural': 'Позиции в заказе',
                'db_table': 'order_item',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'default_related_name': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.SmallIntegerField(verbose_name='Номер стола')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('в ожидании', 'в ожидании'), ('готово', 'готово'), ('оплачено', 'оплачено')], default='в ожидании', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('items', models.ManyToManyField(through='orders.ItemOrder', to='orders.item', verbose_name='Список блюд в заказе')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ('-id', 'table_number'),
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'default_related_name': 'order',
            },
        ),
        migrations.AddField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='orders.order', verbose_name='Заказ клиента'),
        ),
    ]
